/** Los textos del dominio operación, en voz de marca. Un archivo por dominio. */
export const textosOperacion = {
  billetera: {
    titulo: 'Billetera del titular',
    proposito: 'Ver el saldo real de una cuenta para atender una consulta o un reclamo, sin tocar nada.',
    cargando: 'Cargando el saldo de la cuenta',
    disponible: 'Saldo disponible',
    retenido: 'Saldo retenido',
    alCorteDe: 'Al corte de',
    enCero: 'La cuenta está en cero. No es un error de consulta: el titular todavía no recargó, o retiró todo.',
  },
  reclamos: {
    titulo: 'Reclamos',
    proposito: 'Atender cada reclamo dentro de su plazo. El plazo se calculó y se guardó al ingresar: acá no se recalcula.',
    cargando: 'Cargando la bandeja de reclamos',
    sinReclamos: 'No hay reclamos abiertos.',
    plazo: 'Plazo de respuesta',
    norma: 'RNSF Libro 4 Título I — 5 días hábiles, prórroga a 10',
    montoReclamado: 'Monto reclamado',
    responder: 'Responder',
    confirmarResponder: (codigo: string) => `Vas a registrar la respuesta del reclamo ${codigo}. Esta acción queda en el expediente y no se puede deshacer.`,
    estados: {
      INGRESADO: 'Ingresado',
      EN_ANALISIS: 'En análisis',
      RESPONDIDO: 'Respondido',
      CERRADO: 'Cerrado',
      ELEVADO: 'Elevado',
    },
  },
  solicitudesEscaladas: {
    titulo: 'Solicitudes de ingreso escaladas',
    proposito: 'El organizador dejó vencer las 48 horas para resolver: la solicitud pasa a operación con el puntaje descompuesto.',
    cargando: 'Cargando la cola de solicitudes escaladas',
    sinSolicitudes: 'No hay solicitudes escaladas pendientes.',
    plazoOrganizador: 'Vencía para el organizador',
    escaladaEl: 'Escalada el',
    aFavor: 'A favor',
    enContra: 'En contra',
    aceptar: 'Aceptar solicitud',
    rechazar: 'Rechazar solicitud',
    motivoDeRechazo: 'Motivo del rechazo (obligatorio)',
    confirmarAceptar: (nombre: string, grupo: string) => `Vas a dar el cupo a ${nombre} en el grupo ${grupo}. Recién ahí se genera su primera obligación.`,
    confirmarRechazar: (nombre: string, grupo: string) => `Vas a rechazar a ${nombre} en el grupo ${grupo}. El motivo escrito viaja tal cual al postulante.`,
    faltaMotivo: 'Escribí el motivo antes de confirmar el rechazo.',
  },
} as const
