/** Los textos de la admisión humana de grupos, en voz de marca. */
export const textosAdmisiones = {
  titulo: 'Solicitud de ingreso a un grupo',
  proposito:
    'Resolver, con motivo y a tu nombre, si una persona entra a un grupo. El administrador propone y el algoritmo solo recomienda: la decisión final es de backoffice.',
  cargando: 'Cargando el expediente de la solicitud',
  sinDecisiones: 'El administrador del grupo todavía no propuso una decisión. Cuando lo haga, aparece acá y podés resolver.',
  buscarTitulo: 'Abrir una solicitud',
  buscarProposito: 'Abrí una solicitud de ingreso por su identificador, el que llega en el aviso de la solicitud.',
  buscarEtiqueta: 'Identificador de la solicitud',
  buscarAyuda: 'Tiene la forma 8-4-4-4-12 (por ejemplo, 9f1c2b7e-3a54-4d0e-8a61-5b7d2c9e4f10).',
  buscarError: 'Ese identificador no tiene el formato de una solicitud.',
  buscarAccion: 'Abrir solicitud',
  buscarSinListado: 'Todavía no hay un listado de solicitudes pendientes: cada una se abre por su identificador.',
  evidencia: 'Evidencia del algoritmo',
  evidenciaAviso: 'Es una recomendación. No acepta ni rechaza a nadie: lo decide una persona.',
  historial: 'Decisiones registradas',
  fasePropuesta: 'Propuesta del administrador',
  faseResolucion: 'Resolución de backoffice',
  aceptar: 'Aceptar',
  rechazar: 'Rechazar',
  decidio: 'Decidió',
  porAdministrador: 'el administrador del grupo',
  porBackoffice: 'backoffice',
  revision: 'Revisión',
  reservaCupos: 'Se reservaron los cupos. La persona queda pendiente de firmar el reglamento: todavía no es integrante.',
  resolucionCerrada: 'La solicitud ya está resuelta. Esta decisión no se puede cambiar.',
  resolverTitulo: 'Tu resolución',
  resolverAyuda: 'Resolvés sobre la propuesta vigente. Podés contradecirla o contradecir al algoritmo, pero tenés que explicar por qué.',
  decisionEtiqueta: 'Resultado',
  motivoEtiqueta: 'Motivo de la resolución',
  motivoAyuda: 'Obligatorio. Queda en el expediente, con tu nombre y sin posibilidad de editarlo después.',
  motivoRequerido: 'Escribí el motivo: sin motivo no se puede resolver.',
  motivoLargo: 'El motivo admite hasta 1000 caracteres.',
  decisionRequerida: 'Elegí si aceptás o rechazás la solicitud.',
  resolver: 'Resolver solicitud',
  resolviendo: 'Resolviendo…',
  propiaPropuesta: 'Esta propuesta la hiciste vos. La resolución la tiene que dar otra persona.',
  sinPermiso: 'Podés ver el expediente, pero resolver lo hace una persona con rol de administración de la plataforma.',
  confirmada: 'Resolución registrada. La solicitud quedó cerrada.',
  sinConfirmar: 'No pudimos confirmar si tu resolución quedó registrada.',
  sinConfirmarAyuda: 'No la mandes de nuevo a ciegas: primero verificá si ya se registró. Si no está, podés reintentar: el sistema reconoce que es el mismo envío y no lo duplica.',
  verificar: 'Verificar si se registró',
  verificando: 'Verificando…',
  reintentar: 'Reintentar el envío',
  noRegistrada: 'La resolución no se registró. Tus datos siguen acá; podés reintentar.',
  otraResolucion: 'Otra persona ya resolvió esta solicitud. Revisá el historial.',
  sinConexion: 'Estás sin conexión. Lo que escribiste se conserva; vas a poder enviarlo cuando vuelva la señal.',
  cambio: 'La solicitud cambió mientras la mirabas. Actualizamos el expediente: revisá la última decisión antes de resolver.',
} as const
