/** Los textos del dominio publicidad, en voz de marca. Un archivo por dominio (mismo patrón que operación y cumplimiento). */
export const textosPublicidad = {
  anunciantes: {
    titulo: 'Anunciantes',
    proposito: 'Dar de alta un anunciante (organizador o socio comercial) y su cuenta publicitaria. El socio comercial se verifica antes de poder facturar.',
    cargando: 'Cargando los anunciantes',
    sinAnunciantes: 'No hay anunciantes dados de alta todavía.',
    nuevoSocio: 'Postular socio comercial',
    verificarSocio: 'Verificar socio',
    nuevoAnunciante: 'Dar de alta anunciante',
    razonSocial: 'Razón social',
    numeroDocumento: 'Número de documento',
    emailContacto: 'Correo de contacto',
    tipo: 'Tipo de anunciante',
    limiteGasto: 'Límite de gasto mensual (opcional)',
    columnaEstado: 'Estado',
    columnaTipo: 'Tipo',
    columnaLimite: 'Límite mensual',
    estados: {
      POSTULADO: 'Postulado',
      ACTIVO: 'Activo',
      SUSPENDIDO: 'Suspendido',
      DADO_DE_BAJA: 'Dado de baja',
    },
    guardar: 'Guardar',
    cancelar: 'Cancelar',
  },
  campanas: {
    tituloGestion: 'Campañas · gestión',
    propositoGestion: 'Crear campañas y sus conjuntos de anuncios. Quien las crea no es quien las aprueba (R-PUB-05 aplicado a campañas, mismo patrón que desembolsos).',
    tituloAprobacion: 'Campañas · aprobación',
    propositoAprobacion: 'Aprobar o rechazar campañas en revisión. Un rechazo exige motivo escrito, y queda en el evento de la campaña.',
    cargando: 'Cargando las campañas',
    sinCampanas: 'No hay campañas registradas todavía.',
    nuevaCampana: 'Crear campaña',
    nombre: 'Nombre de la campaña',
    objetivo: 'Objetivo',
    presupuestoTotal: 'Presupuesto total',
    fechaInicio: 'Fecha de inicio',
    aprobar: 'Aprobar campaña',
    rechazar: 'Rechazar campaña',
    motivoDeRechazo: 'Motivo del rechazo',
    faltaMotivo: 'El rechazo exige un motivo escrito.',
    confirmarAprobar: (nombre: string) => `Vas a aprobar la campaña «${nombre}». Empieza a entregar de inmediato.`,
    confirmarRechazar: (nombre: string) => `Vas a rechazar la campaña «${nombre}». Esta acción queda en el expediente.`,
    columnaEstado: 'Estado',
    columnaPresupuesto: 'Presupuesto',
    estados: {
      BORRADOR: 'Borrador',
      EN_REVISION: 'En revisión',
      ACTIVA: 'Activa',
      PAUSADA: 'Pausada',
      FINALIZADA: 'Finalizada',
      RECHAZADA: 'Rechazada',
    },
    guardar: 'Guardar',
    cancelar: 'Cancelar',
  },
  moderacion: {
    titulo: 'Moderación de piezas creativas',
    proposito: 'Toda pieza nace PENDIENTE y solo se puede usar en un anuncio si queda APROBADA acá. Quien la subió no puede moderarla (R-PUB-05).',
    cargando: 'Cargando la cola de moderación',
    sinPiezas: 'No hay piezas pendientes de moderación.',
    columnaTitulo: 'Título',
    columnaAnunciante: 'Anunciante',
    columnaRecurso: 'Recurso',
    columnaEstado: 'Estado moderación',
    aprobar: 'Aprobar pieza',
    rechazar: 'Rechazar pieza',
    motivoDeRechazo: 'Motivo del rechazo',
    faltaMotivo: 'El rechazo exige un motivo escrito.',
    esAutorNoPuedeModerar: 'Quien subió esta pieza no puede moderarla.',
    confirmarAprobar: (titulo: string) => `Vas a aprobar la pieza «${titulo}». Queda disponible para programarse en un anuncio.`,
    confirmarRechazar: (titulo: string) => `Vas a rechazar la pieza «${titulo}». No podrá usarse en ningún anuncio.`,
    estados: {
      PENDIENTE: 'Pendiente',
      APROBADA: 'Aprobada',
      RECHAZADA: 'Rechazada',
    },
  },
  desempeno: {
    titulo: 'Desempeño publicitario',
    proposito: 'Lo consumido en el período, al centavo. Es el mismo dato que usa la liquidación: si acá y en la factura hubiera dos números distintos, sería un defecto del sistema, no una diferencia de vista.',
    cargando: 'Cargando el consumo del período',
    periodo: 'Período',
    cuenta: 'Cuenta publicitaria',
    totalConsumido: 'Total consumido en el período',
    mismoDatoQueLiquidacion: 'Esta cifra es la misma que usa CU-114 para facturar: un único origen de dato.',
    buscar: 'Consultar',
  },
  liquidacion: {
    titulo: 'Liquidación y facturación',
    proposito: 'Factura el gasto publicitario del período sobre el mismo consumo que muestra el panel de desempeño. Un período por cuenta, una sola vez (R-PUB-06).',
    cargando: 'Cargando el consumo del período',
    periodo: 'Período',
    cuenta: 'Cuenta publicitaria',
    totalAFacturar: 'Total a facturar',
    liquidar: 'Liquidar período',
    yaLiquidado: 'Este período ya fue liquidado para esta cuenta.',
    sinConsumo: 'No hay consumo en el período: no hay obligación de facturar cero.',
    confirmarLiquidar: (periodo: string) => `Vas a liquidar el período ${periodo}. Genera la factura de publicidad y no se puede repetir.`,
    columnaEstado: 'Estado de la factura',
    columnaMonto: 'Monto total',
    estados: {
      GENERADA: 'Generada (sin comprobante)',
      FACTURADA: 'Facturada',
      COBRADA: 'Cobrada',
      ANULADA: 'Anulada',
    },
  },
}
