/** Los textos del dominio sistemas, en voz de marca. Un archivo por dominio (igual patrón que operación). */
export const textosSistemas = {
  menu: {
    titulo: 'Sistemas',
    servicios: 'Servicios y SLO',
    despliegues: 'Despliegues e interruptores',
    baseDeDatos: 'Base y migraciones',
    respaldos: 'Respaldos',
    proveedores: 'Proveedores',
    outbox: 'Outbox y descartados',
    webhooks: 'Webhooks',
    accesos: 'Accesos',
    incidentes: 'Incidentes',
  },
  bloqueo: {
    titulo: 'No tenés acceso a este backoffice',
    porque: 'Este es el backoffice de sistemas. Hace falta el rol PLATAFORMA o SEGURIDAD; un rol financiero no ve esta información.',
  },
  servicios: {
    proposito: 'Ver el estado de cada servicio y su presupuesto de error del SLO, para decidir si hay que actuar.',
    titulo: 'Estado de servicios',
    cargando: 'Cargando el estado de los servicios',
    vacio: 'Todavía no hay servicios reportando estado.',
  },
  despliegues: {
    proposito: 'Ver los despliegues recientes y accionar interruptores. Un interruptor que toca dinero exige dos personas.',
    titulo: 'Despliegues e interruptores',
    cargando: 'Cargando despliegues e interruptores',
    vacio: 'No hay despliegues ni interruptores registrados.',
    confirmarPrimeraPersona: 'Pediste el cambio. Falta que otra persona lo confirme: no podés confirmarlo vos misma/o.',
    confirmarSegundaPersona: 'Confirmar el cambio (segunda persona)',
    dobleConfirmacionTitulo: 'Este interruptor toca dinero',
    dobleConfirmacionCuerpo: 'Requiere que dos personas distintas lo confirmen. Ya lo pediste vos; hace falta otra sesión para cerrarlo.',
  },
  baseDeDatos: {
    proposito: 'Ver el estado de la base y qué migraciones están aplicadas o pendientes.',
    titulo: 'Base y migraciones',
    cargando: 'Cargando el estado de la base',
    vacio: 'No hay migraciones registradas.',
  },
  respaldos: {
    proposito: 'Ver los respaldos y cuándo se probó por última vez la restauración de cada uno.',
    titulo: 'Respaldos',
    cargando: 'Cargando los respaldos',
    vacio: 'No hay respaldos registrados.',
    restauracionVencida: 'Restauración vencida: hace más de 30 días que no se prueba.',
  },
  proveedores: {
    proposito: 'Ver los proveedores externos activos, con su costo real del último período.',
    titulo: 'Proveedores',
    cargando: 'Cargando los proveedores',
    vacio: 'No hay proveedores registrados.',
  },
  outbox: {
    proposito: 'Ver los mensajes salientes y la cola de descartados, cada uno con su motivo.',
    titulo: 'Outbox y descartados',
    cargando: 'Cargando la bandeja de salida',
    vacio: 'No hay mensajes en la bandeja de salida.',
    tituloDescartados: 'Descartados',
    vacioDescartados: 'No hay mensajes descartados.',
  },
  webhooks: {
    proposito: 'Ver los webhooks entrantes y salientes, con su último estado de entrega.',
    titulo: 'Webhooks',
    cargando: 'Cargando los webhooks',
    vacio: 'No hay webhooks configurados.',
  },
  accesos: {
    proposito: 'Ver quién tiene acceso a qué, para revisar o revocar.',
    titulo: 'Accesos',
    cargando: 'Cargando los accesos',
    vacio: 'No hay accesos registrados.',
  },
  incidentes: {
    proposito: 'Ver los incidentes abiertos y cerrados, con su impacto y su causa raíz.',
    titulo: 'Incidentes',
    cargando: 'Cargando los incidentes',
    vacio: 'No hay incidentes registrados.',
  },
} as const
