/** Los textos del dominio contabilidad (ERP, CU-100 a CU-106), en voz de marca. Un archivo por dominio. */
export const textosContabilidad = {
  periodo: {
    titulo: 'Períodos contables',
    proposito: 'Fijar el mes: una vez cerrado, nadie puede asentar hacia atrás y los libros dejan de moverse solos.',
    cargando: 'Cargando los períodos del ejercicio',
    enCero: 'Este ejercicio todavía no tiene períodos.',
    asentar: 'Asentar en este período',
    cerrar: 'Cerrar el período',
    cerrarIrreversible: 'El cierre es irreversible: no existe reabrir un período.',
    confirmarCierre: (nombre: string) => `Vas a cerrar ${nombre}. El cierre es irreversible y ningún asiento podrá registrarse en ese mes después.`,
    motivoCerrado: 'Período cerrado: no se puede asentar en él. La corrección va en el período abierto siguiente, con glosa que lo referencie.',
    motivoNoEsElMasAntiguo: 'Hay un mes anterior todavía abierto: los períodos se cierran en orden estricto.',
    cuadre: 'Cuadre del mes',
    debe: 'Total debe',
    haber: 'Total haber',
    estados: { ABIERTO: 'Abierto', CERRADO: 'Cerrado' } as const,
    glosa: 'Glosa del cierre',
  },
  presupuesto: {
    titulo: 'Presupuesto por centro de costo',
    proposito: 'Comparar lo que el Directorio autorizó antes del período contra lo que se gastó: la desviación es un hecho, no una sensación.',
    cargando: 'Cargando las partidas del presupuesto',
    enCero: 'No hay partidas presupuestarias para este ejercicio.',
    noBloquea: 'El presupuesto mide el gasto, no lo bloquea: pasarse registra la desviación para que alguien la explique.',
    presupuestado: 'Presupuestado',
    ejecutado: 'Ejecutado',
    desviacion: 'Desviación',
    sobreEjecutado: 'Sobre lo presupuestado',
    estados: { BORRADOR: 'Borrador', APROBADO: 'Aprobado', CERRADO: 'Cerrado' } as const,
  },
  compras: {
    titulo: 'Compras y cuentas por pagar',
    proposito: 'Que ninguna obligación de pagar exista antes de una orden autorizada, y que quien aprueba la factura no sea quien la paga.',
    ordenes: 'Órdenes de compra',
    facturas: 'Facturas de proveedor',
    cargandoOrdenes: 'Cargando las órdenes de compra',
    cargandoFacturas: 'Cargando las facturas de proveedor',
    enCeroOrdenes: 'No hay órdenes de compra con estos filtros.',
    enCeroFacturas: 'No hay facturas de proveedor con estos filtros.',
    pagar: 'Registrar el pago',
    vencimiento: 'Vence',
    saldoPendiente: 'Saldo pendiente',
    segregacion: 'Quien aprobó la factura no puede autorizar su pago (R-CTB-05). Esta cuenta aprobó esta factura.',
    sinPermisoDePago: 'Registrar el pago es de Tesorería: esta cuenta no tiene CONTABILIDAD_ERP_PAGAR.',
    confirmarPago: (numero: string) => `Vas a registrar el pago de la factura ${numero}. El pago es append-only: para corregirlo hace falta un movimiento inverso.`,
    estadosOrden: { BORRADOR: 'Borrador', APROBADA: 'Aprobada', RECIBIDA: 'Recibida', CANCELADA: 'Cancelada' } as const,
    estadosFactura: { REGISTRADA: 'Registrada', APROBADA: 'Aprobada', PAGADA_PARCIAL: 'Pagada en parte', PAGADA: 'Pagada', ANULADA: 'Anulada' } as const,
  },
  cobros: {
    titulo: 'Cuentas por cobrar',
    proposito: 'Que toda plata que un tercero le debe a la empresa tenga estado verificable, y ninguna se pierda de vista.',
    cargando: 'Cargando las cuentas por cobrar',
    enCero: 'No hay cuentas por cobrar con estos filtros.',
    cobrar: 'Registrar el cobro',
    origen: 'Origen',
    saldoPendiente: 'Saldo pendiente',
    incobrable: 'Cuenta declarada incobrable: no admite cobros.',
    confirmarCobro: (origen: string) => `Vas a registrar un cobro contra la cuenta de origen ${origen}. El cobro no puede exceder el saldo pendiente.`,
    estados: { PENDIENTE: 'Pendiente', COBRADA_PARCIAL: 'Cobrada en parte', COBRADA: 'Cobrada', INCOBRABLE: 'Incobrable' } as const,
  },
  activos: {
    titulo: 'Activos fijos',
    proposito: 'Repartir el gasto de un bien de uso a lo largo de su vida útil, para que el mes de la compra no se coma el resultado del año.',
    cargando: 'Cargando el inventario de activos',
    enCero: 'No hay activos fijos con estos filtros.',
    depreciar: 'Depreciar en el período',
    costo: 'Costo de adquisición',
    acumulada: 'Depreciación acumulada',
    valorEnLibros: 'Valor en libros',
    agotado: 'El valor en libros ya llegó al residual: no genera depreciación nueva.',
    dadoDeBaja: 'El activo está fuera de uso: no se deprecia.',
    yaCorrido: 'Ya tiene cuota calculada en este período.',
    estados: { ACTIVO: 'En uso', DADO_DE_BAJA: 'Dado de baja', VENDIDO: 'Vendido' } as const,
  },
  estados: {
    titulo: 'Estados financieros',
    proposito: 'Que «el balance de marzo» sea una fotografía guardada y verificable, no un cálculo que da distinto cada vez que alguien lo pide.',
    cargando: 'Generando el estado financiero',
    generar: 'Generar el estado financiero',
    descargar: 'Descargar el documento',
    hash: 'Hash del contenido (lo calculó el backend)',
    hashExplicacion: 'El hash viene del backend junto con el estado financiero. El cliente no lo recalcula: solo lo muestra y lo compara con el del documento descargado.',
    cuadra: 'El estado cuadra',
    noCuadra: 'El estado NO cuadra: hay un descuadre que resolver antes de usarlo.',
    provisorio: 'Provisorio: el período todavía está abierto. No reemplaza al definitivo posterior al cierre.',
    definitivo: 'Definitivo: el período está cerrado.',
    hashDiscrepante: 'El documento descargado no corresponde al estado financiero generado: el hash del archivo no coincide con el que devolvió el backend. No se entrega el archivo.',
    tipos: { BALANCE_GENERAL: 'Balance general', ESTADO_RESULTADOS: 'Estado de resultados' } as const,
  },
} as const
