/**
 * publicidad
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntradaRevision { 
    decision: EntradaRevisionDecisionEnum;
    /**
     * Obligatorio cuando la decision es RECHAZADA.
     */
    motivo?: string | null;
}
export enum EntradaRevisionDecisionEnum {
    Aprobada = 'APROBADA',
    Rechazada = 'RECHAZADA'
};



