/**
 * publicidad
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Conjunto } from './conjunto';


export interface EntradaCampana { 
    cuentaPublicitariaId: string;
    nombre: string;
    objetivo: EntradaCampanaObjetivoEnum;
    /**
     * Importe como CADENA decimal. Un number JSON es un doble.
     */
    presupuestoTotal: string;
    moneda: EntradaCampanaMonedaEnum;
    fechaInicio: string;
    fechaFin?: string | null;
    conjuntos: Array<Conjunto>;
}
export enum EntradaCampanaObjetivoEnum {
    VisibilidadMarca = 'VISIBILIDAD_MARCA',
    Trafico = 'TRAFICO',
    PostulacionGrupo = 'POSTULACION_GRUPO',
    DescargaApp = 'DESCARGA_APP',
    Conversion = 'CONVERSION'
};
export enum EntradaCampanaMonedaEnum {
    Bob = 'BOB',
    Usd = 'USD'
};



