/**
 * publicidad
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EntradaAnunciante { 
    tipo: EntradaAnuncianteTipoEnum;
    /**
     * Obligatorio si tipo es ORGANIZADOR, y prohibido si no (R-PUB-01).
     */
    organizadorId?: string | null;
    /**
     * Obligatorio si tipo es SOCIO_COMERCIAL, y prohibido si no.
     */
    socioComercialId?: string | null;
    razonSocialFacturacion: string;
    /**
     * Opcional. Sin limite, la cuenta no tiene techo mensual.
     */
    limiteGastoMensual?: string | null;
    moneda: EntradaAnuncianteMonedaEnum;
}
export enum EntradaAnuncianteTipoEnum {
    Organizador = 'ORGANIZADOR',
    SocioComercial = 'SOCIO_COMERCIAL'
};
export enum EntradaAnuncianteMonedaEnum {
    Bob = 'BOB',
    Usd = 'USD'
};



