/**
 * publicidad
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SalidaCampana { 
    campanaPublicitariaId: string;
    estado: SalidaCampanaEstadoEnum;
    /**
     * Importe como CADENA decimal. Un number JSON es un doble.
     */
    presupuestoTotal: string;
}
export enum SalidaCampanaEstadoEnum {
    Borrador = 'BORRADOR',
    EnRevision = 'EN_REVISION',
    Activa = 'ACTIVA',
    Pausada = 'PAUSADA',
    Finalizada = 'FINALIZADA',
    Rechazada = 'RECHAZADA'
};



