/** Los textos del dominio cumplimiento y gobierno, en voz de marca. Un archivo por dominio. */
export const textosCumplimiento = {
  verificaciones: {
    titulo: 'Verificación de identidad',
    proposito:
      'Mirar el documento y la cara de quien abre una cuenta, y decidir. La decisión es de una persona y queda con su nombre.',
    cargando: 'Cargando los expedientes',
    filtrar: 'Filtrar por estado',
    sinPendientes: 'No hay expedientes esperando. Cuando alguien termine su alta, aparece acá.',
    sinDocumento: 'Sin documento cargado',
    fotos: 'Fotos',
    fotoDe: 'Foto del expediente de',
    faltante: '(falta)',
    expedienteIncompleto: 'Faltan fotos. No se aprueba un expediente que no se puede mirar entero.',
    motivo: 'Motivo',
    motivoAyuda: 'Obligatorio para rechazar. Quien recibe el rechazo tiene derecho a saber por qué.',
    aprobar: 'Aprobar',
    rechazar: 'Rechazar',
  },
  alertas: {
    titulo: 'Alertas de riesgo temprano',
    proposito: 'Ver por qué el modelo sugiere acompañar a un grupo, antes de que incumpla — nunca una condena.',
    cargando: 'Cargando la alerta',
    enCero: 'No hay alertas activas para este grupo.',
    veredicto: 'Alerta de riesgo temprano: acompañar',
    aviso: 'Esto no es un veredicto sobre el grupo. Separa lo que ya pasó (hechos registrados) de lo que el modelo estima.',
    hechos: 'Hechos registrados',
    estimaciones: 'Estimaciones del modelo',
  },
  casos: {
    titulo: 'Caso de cumplimiento',
    proposito: 'Investigar una alerta hasta una decisión motivada, con el debido proceso completo.',
    causal: 'Causal del catálogo',
    causalAyuda: 'Elegí la causal antes de poder confirmar. No se rechaza ni se observa sin causal.',
    confirmar: 'Confirmar decisión',
    sinCausal: 'Elegí una causal del catálogo para habilitar la confirmación.',
    etapas: ['Causal', 'Notificación', 'Plazo', 'Descargo', 'Decisión motivada', 'Apelación'],
    borradorGuardado: 'Borrador guardado',
    borradorRecuperado: 'Se recuperó un borrador de esta narrativa',
  },
  actas: {
    titulo: 'Acta de comité',
    proposito: 'Registrar la sesión con voto nominal, y no cerrarla sin quórum.',
    quorum: 'Quórum',
    sinQuorum: 'No hay quórum: sesionaron menos personas que el mínimo del comité. No se puede cerrar el acta.',
    composicionIncompleta: 'Falta en la mesa un rol que la composición del comité exige.',
    cerrar: 'Cerrar acta',
    abstencion: 'Abstención',
    motivoAbstencion: 'Motivo de la abstención',
  },
  reclamos: {
    titulo: 'Reclamo del consumidor',
    proposito: 'Responder un reclamo dentro del plazo guardado al registrarlo, nunca uno recalculado en el cliente.',
    plazo: 'Plazo de respuesta',
    norma: 'ASFI · Reglamento de atención al consumidor financiero',
    respuesta: 'Respuesta',
    enviar: 'Enviar respuesta',
  },
  organizadores: {
    titulo: 'Habilitación de organizador',
    proposito: 'Ver si un organizador está habilitado para abrir grupos, y hasta dónde.',
    cargando: 'Consultando la habilitación',
    habilitar: 'Habilitar tras capacitación',
    habilitado: 'Habilitado',
    noHabilitado: 'No habilitado',
    nivel: 'Nivel',
    limiteDeGrupos: 'Límite de grupos',
    limiteDeMonto: 'Límite de monto',
    gruposActivos: 'Grupos activos',
  },
} as const
