export { ESCENARIOS, cabeceraDeEscenario, type Escenario } from './escenarios'
export { muestraDe, uuidDe, type Modo } from './muestra'
export { resolver } from './referencias'
export { METODOS, type Contrato, type Esquema, type Metodo, type Operacion, type Respuesta } from './tipos'
export { ejemploDe, type ArchivoDeEjemplos, type EjemploDeEscenario } from './ejemplos'
